services:
  mongo:
    image: mongo:5
    container_name: mongo-local
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    image: niharlandge/crud-mean-backend:latest
    container_name: tutorials-backend
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://mongo:27017/dd_db
      PORT: 8080
    depends_on:
      - mongo

  frontend:
    image: niharlandge/crud-mean-frontend:latest
    container_name: tutorials-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data:
